service: ringcentral-trello-notification-app
provider:
  stage: ${opt:stage, 'prod'}
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 256
  environment: ${file(./env.yml)}
  profile: default
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - lambda:InvokeFunction
  #     Resource: ""
  deploymentBucket:
    tags:
      Department: dev
      Owner: Your name
      Stage: production
      Environment: your-env-tag
      Team: your-team
      Name: ringcentral-trello-notification-app
  tags:
    Department: dev
    Owner: Your name
    Stage: production
    Environment: your-env-tag
    Team: your-team
    Name: ringcentral-trello-notification-app
package:
  excludeDevDependencies: true
  include:
    - '.json'
    - '.js'
    - 'node_modules/**'
functions:
  app:
    handler: lambda.app
    # role: arn:aws:iam::111111:role/xxxx-prod-us-east-1-lambdaRole
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: false
resources:
  Resources:
    rcWebhooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: trello-rc-notification-rc-webhooks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    trelloWebhooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: trello-rc-notification-trello-webhooks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    trelloUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: trello-rc-notification-trello-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
