@startuml

title RingCentral App Add-In Framework Local Developement Workflow

autonumber

Database "Database" as DB
control "Server" as SERVER
control "RingCentral Notification App Tool" as G
control "3rd Party Service" as T
actor "RC App" as RC

group setup

    group register RC_WEBHOOK
    G -> SERVER: fill in 'App Url' and 'Webhook Url', and Apply
    activate SERVER
    SERVER -->o G: copy SERVER_WEBHOOK(has subscriptionId) over to 3rd party
    SERVER -->o DB: save subscriptionId and RC_WEBHOOK to database
    deactivate SERVER
    end
end

group transformation
    T -> SERVER: notification to SERVER_WEBHOOK
    activate SERVER
    SERVER -> DB: query subscription id
    activate DB
    DB --> SERVER: return RC_WEBHOOK
    deactivate DB
    SERVER -->o RC: transform notification message and send to RC_WEBHOOK
    deactivate SERVER
end

group interactive message - for KNOWN user
    RC -> SERVER: request to perform action with RC_USER_ID
    SERVER --> DB: get user
    DB --> SERVER: known, return accessToken
    SERVER --> T: perform action
    SERVER --> RC: notify user about the result
end

group interactive message - for UNKNOWN user
    RC -> SERVER: request to perform action with RC_USER_ID
    SERVER --> DB: get user
    DB --> SERVER: unknown
    SERVER --> RC: prompt for auth
    RC --> SERVER: retun accessCode for token exchange
    SERVER --> T: token exchange
    T --> SERVER: token
    SERVER --> DB: register user info
    SERVER --> T: perform action
    SERVER --> RC: notify user about the result
end

@enduml